### ISSUE TITLE
stage0 bootstrap fails to build musl due to relr section

### ISSUE THREAD

**Issue by wezm** [chimera-linux/cports#512] opened 2023-09-08 11:11 UTC
I attempted to do a stage0 bootstrap on an x86_64 Chimera host. It fails with the following error:

```
=> musl-1.2.4-r1: running post_install hook: 007_strip_debug...
strip: elf_update() failed: Invalid section descriptor
=> musl-1.2.4-r1: ERROR: failed to strip usr/bin/getent
```

After some investigation I worked out that the problematic section header type is 19, which appears to be [SHT_RELR](https://git.musl-libc.org/cgit/musl/tree/include/elf.h?h=v1.2.4#n388). It seems that [`elftoolchain` can't handle/doesn't know about the RELR section](https://github.com/elftoolchain/elftoolchain/blob/f7e9afc6f9ad0d84ea73b4659c5d6d13275d2306/common/sys/elfconstants.m4#L1315):

```
$ readelf -S bldroot/usr/bin/getent
There are 27 section headers, starting at offset 0x3090:

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .interp           PROGBITS         00000000000002a8  000002a8
       0000000000000019  0000000000000000   A       0     0     1
  [ 2] .note.gnu.build-i NOTE             00000000000002c4  000002c4
       0000000000000018  0000000000000000   A       0     0     4
  [ 3] .dynsym           DYNSYM           00000000000002e0  000002e0
       0000000000000600  0000000000000018   A       5     1     8
  [ 4] .gnu.hash         GNU_HASH         00000000000008e0  000008e0
       0000000000000024  0000000000000000   A       3     0     8
  [ 5] .dynstr           STRTAB           0000000000000904  00000904
       00000000000002b6  0000000000000000   A       0     0     1
  [ 6] .rela.dyn         RELA             0000000000000bc0  00000bc0
       0000000000000060  0000000000000018   A       3     0     8
  [ 7] .relr.dyn         <unknown: 0x13>  0000000000000c20  00000c20
       0000000000000018  0000000000000008   A       0     0     8
⋮
```

I think the regression happened in a66f8f31016ae1ddcd4a24b8bea5649a4060a15a. Not sure if the solution is to restore `!relr`, skip stripping, try to get `elftoolchain` fixed, or something else but restoring `!relr` to the musl template does resolve the issue as expected. Continuing the bootstrap results in the same issue being hit again when building `attr-progs`:

```
=> attr-progs-2.5.1-r0: ERROR: failed to strip usr/bin/getfattr
```

which I suppose is to be expected.

**Comment by nekopsykose** [comment] 2023-09-08 11:26
not sure if a66f8f31016ae1ddcd4a24b8bea5649a4060a15a is really the cause, because the linker would generate DT_RELR for any build (like the attr one after it), and elftoolchain will fail to strip it. skipping !relr on musl won't fix the one after, so elftoolchain-strip would have to handle it.

that said, relr has been there for a long time, and i would have imagined q66 has tried a bootstrap in between then and now, so it might be something else..

**Comment by nekopsykose** [comment] 2023-09-08 11:28
the easiest specific fix is setting !relr globally for stage0 probably

**Comment by nekopsykose** [comment] 2023-09-08 11:30
e.g. `src/cbuild/core/profile.py:398` and change True to include stage > 0, and change the calls to it to pass stage or w/e. in `src/cbuild/core/template.py:2071` you can see after 0 llvm- tools are used instead

**Comment by nekopsykose** [comment] 2023-09-08 11:31
but it might be better to get someone to improve elftoolchain a little :p

**Comment by wezm** [comment] 2023-09-08 12:11
> the easiest specific fix is setting !relr globally for stage0 probably

Yep that was the next thing I tried (ran into a different issue after that I'll look into later).

> in `src/cbuild/core/template.py:2071` you can see after 0 llvm- tools are used instead

Ahh that explains a lot

**Closed** 2023-09-08 17:03 UTC
