### ISSUE TITLE
contrib/firefox: repeatable tab crash

### ISSUE THREAD

**Issue by wezm** [chimera-linux/cports#2133] opened 2024-06-03 23:21 UTC
I'm reporting this here as I can visit this page without crashing on an Arch system. 

Visting https://thisweekinbevy.com/issue/2024-06-03-tiny-glade-vj-performances-and-2d-lighting on an up-to-date (as of this morning) x86_64 Chimera system reliably crashes the Firefox tab. I tried to collect a stack trace but did not succeed.

The kernel logs say:

> 2024-06-04 09:03:55 info kernel: traps: Isolated Web Co[7750] general protection fault ip:7cb01c159bd4 sp:7ffef807df60 error:0 in libxul.so[7cb016ae0000+5825000]

Firefox says (this was a different instance hence the different PIDs):

> [Parent 9019, IPC I/O Parent] WARNING: process 9538 exited on signal 11: file ipc/chromium/src/base/process_util_posix.cc:335

This is what I tried:

- Install `firefox-dbg`
- Start Firefox
- `lldb --attach-pid <pid>` for each process listed by `pgrep Iso`

It seems this isn't enough as it spaws a new process for the tab and that's the one that crashes.

I also tried to turn on core dumps but I'm not sure if this is the right way, since I never saw a core file:

`ulimit -c unlimited`

Any guidance on how to further debug this would be most welcome.

**Comment by nekopsykose** [comment] 2024-06-04 08:16
this happens ever since the first rebuild with llvm18, never managed to figure out what causes it. i think @ptrcnull got the closest but it's behind a thousand layers of rust ffi in the backtrace..

**Comment by nekopsykose** [comment] 2024-06-04 08:16
it happens when loading any page with xml (or that loads an xml element)

**Comment by ptrcnull** [comment] 2024-06-05 10:09
<details>
<summary>partial stacktrace from GDB</summary>

```
(gdb) bt
#0  style::gecko_bindings::sugar::ns_t_array::{impl#0}::deref<nsstring::nsString> (self=<optimized out>, self=<optimized out>, self=<optimized out>)
    at servo/components/style/gecko_bindings/sugar/ns_t_array.rs:18
#1  style::values::generics::CounterStyle::from_gecko_value (gecko_value=<optimized out>) at servo/components/style/gecko/values.rs:69
#2  0x00007ff772c8dfc5 in style::properties::generated::gecko::GeckoList::clone_list_style_type (self=<optimized out>)
    at obj-x86_64-pc-linux-musl/x86_64-chimera-linux-musl/release/build/style-ba08e944926c2248/out/properties.rs:58672
#3  style::style_adjuster::StyleAdjuster::adjust_for_marker_pseudo (self=<optimized out>) at servo/components/style/style_adjuster.rs:899
#4  0x00007ff772ae3587 in style::style_adjuster::StyleAdjuster::adjust<style::gecko::wrapper::GeckoElement>
    (self=0x7fffbda78608, layout_parent_style=0x7ff761d0c198, element=<error reading variable: Cannot access memory at address 0x0>) at servo/components/style/style_adjuster.rs:1003
#5  style::properties::cascade::apply_declarations<style::gecko::wrapper::GeckoElement, style::properties::cascade::DeclarationIterator>
    (stylist=<optimized out>, pseudo=..., rules=<optimized out>, guards=0x7fffbda79040, iter=..., parent_style=..., layout_parent_style=..., first_line_reparenting=..., cascade_mode=..., cascade_input_flags=..., rule_cache=..., rule_cache_conditions=0x7fffbda78d00, element=...) at servo/components/style/properties/cascade.rs:378
#6  0x00007ff772b34ba6 in style::properties::cascade::cascade_rules<style::gecko::wrapper::GeckoElement>
    (stylist=<optimized out>, pseudo=<error reading variable: Cannot access memory at address 0x0>, rule_node=<optimized out>, guards=<optimized out>, parent_style=<error reading variable: Cannot access memory at address 0x0>, layout_parent_style=<error reading variable: Cannot access memory at address 0x0>, first_line_reparenting=<error reading variable: Cannot access memory at address 0x0>, cascade_mode=<error reading variable: Cannot access memory at address 0x0>, cascade_input_flags=..., rule_cache=<error reading variable: Cannot access memory at address 0x0>, rule_cache_conditions=<optimized out>, element=<error reading variable: Cannot access memory at address 0x0>) at servo/components/style/properties/cascade.rs:197
#7  style::properties::cascade::cascade<style::gecko::wrapper::GeckoElement>
    (stylist=<optimized out>, pseudo=<error reading variable: Cannot access memory at address 0x0>, rule_node=<optimized out>, guards=<optimized out>, parent_style=<error reading variable: Cannot access memory at address 0x0>, layout_parent_style=<error reading variable: Cannot access memory at address 0x0>, first_line_reparenting=<error reading variable: Cannot access memory at address 0x0>, visited_rules=<error reading variable: Cannot access memory at address 0x0>, cascade_input_flags=..., rule_cache=<error reading variable: Cannot access memory at address 0x0>, rule_cache_conditions=<optimized out>, element=<error reading variable: Cannot access memory at address 0x0>) at servo/components/style/properties/cascade.rs:81
#8  style::stylist::Stylist::cascade_style_and_visited<style::gecko::wrapper::GeckoElement>
    (self=0x7ff776e21088, element=..., pseudo=..., inputs=..., guards=0x7fffbda79040, parent_style=..., layout_parent_style=..., first_line_reparenting=..., rule_cache=<error reading variable: Cannot access memory at address 0x0>, rule_cache_conditions=0x7fffbda78d00) at servo/components/style/stylist.rs:1177
#9  0x00007ff772bb5393 in style::stylist::Stylist::compute_pseudo_element_style_with_inputs<style::gecko::wrapper::GeckoElement>
    (self=<optimized out>, inputs=<error reading variable: Cannot access memory at address 0x0>, pseudo=<optimized out>, guards=<optimized out>, parent_style=<error reading variable: Cannot access memory at address 0x0>, element=<error reading variable: Cannot access memory at address 0x0>) at servo/components/style/stylist.rs:1116
#10 style::stylist::Stylist::lazily_compute_pseudo_element_style<style::gecko::wrapper::GeckoElement>
    (self=0x7ff776e21088, guards=0x7fffbda79040, pseudo=0x7fffbda790d8, rule_inclusion=style::stylist::RuleInclusion::All, originating_element_style=0x7ff761d0c198, matching_fn=..., element=..., is_probe=<optimized out>) at servo/components/style/stylist.rs:1080
#11 geckoservo::glue::get_pseudo_style
    (guard=0x7fffbda79010, pseudo=0x7fffbda790d8, rule_inclusion=style::stylist::RuleInclusion::All, styles=0x7ff7775bf2c8, stylist=0x7ff776e21088, matching_func=..., element=..., inherited_styles=<error reading variable: Cannot access memory at address 0x0>, is_probe=<optimized out>) at servo/ports/geckolib/glue.rs:4281
#12 geckoservo::glue::Servo_ResolvePseudoStyle
    (element=<optimized out>, pseudo_type=<optimized out>, functional_pseudo_parameter=<optimized out>, is_probe=<optimized out>, inherited_style=..., raw_data=<optimized out>)
    at servo/ports/geckolib/glue.rs:4110
#13 0x00007ff77083731f in mozilla::ServoStyleSet::ResolvePseudoElementStyle
    (this=<optimized out>, aOriginatingElement=..., aType=<optimized out>, aFunctionalPseudoParameter=<optimized out>, aParentStyle=0x7ff761d0c198, aIsProbe=mozilla::ServoStyleSet::IsProbe::Yes) at ./layout/style/ServoStyleSet.cpp:473
#14 0x00007ff7708dd760 in mozilla::ServoStyleSet::ProbePseudoElementStyle
    (this=0x7ff776d2c8a0, aOriginatingElement=..., aType=mozilla::PseudoStyleType::marker, aFunctionalPseudoParameter=0x0, aParentStyle=0x66) at ../../dist/include/mozilla/ServoStyleSet.h:225
#15 nsCSSFrameConstructor::CreateGeneratedContentItem
    (this=0x7ff777620990, aState=..., aParentFrame=0x7ff76b067ae0, aOriginatingElement=..., aStyle=..., aPseudoElement=mozilla::PseudoStyleType::marker, aItems=..., aExtraFlags=...)
    at ./layout/base/nsCSSFrameConstructor.cpp:1864
```

</details>

submitted as https://crash-stats.mozilla.org/report/index/62b6fed2-11fc-4467-b6d3-960990240605

for what it's worth, i can't reproduce this on a nightly built outside of cbuild, so it could be either fixed in a newer version, or caused by some flag that's being set automatically

**Closed** 2024-06-06 11:58 UTC
